import LyricsWrapper from '@/site/record/LyricsWrapper';
import clsx from 'clsx';

export default function Track() {
  return(
    <div id="track-lyrics" className={clsx('text-2xl flex flex-col')}>
      <div>
        <LyricsWrapper>
          <ruby>
          サヨナラ
            <rt>さよなら</rt>
          </ruby>
        が
          <ruby>
          近
            <rt>ちか</rt>
          </ruby>
        づいている
        </LyricsWrapper>
        <LyricsWrapper>
        その
          <ruby>
        意味
            <rt>いみ</rt>
          </ruby>
        に
          <ruby>
        悩
            <rt>なや</rt>
          </ruby>
        まされる
        </LyricsWrapper>
      </div>
      <div>
        <LyricsWrapper>
          <ruby>
        八
            <rt>はち</rt>
          </ruby>
        の
          <ruby>
        字
            <rt>じ</rt>
          </ruby>
        に
          <ruby>
        曲
            <rt>ま</rt>
          </ruby>
        がった
          <ruby>
        君
            <rt>きみ</rt>
          </ruby>
        の
          <ruby>
        眉
            <rt>まゆ</rt>
          </ruby>
        が
        </LyricsWrapper>
        <LyricsWrapper>
          <ruby>
        懐
            <rt>なつ</rt>
          </ruby>
        かしい
          <ruby>
        思
            <rt>おも</rt>
          </ruby>
        い
          <ruby>
        出
            <rt>だ</rt>
          </ruby>
        すよ
        </LyricsWrapper>
      </div>
      <span>
        <ruby>
          出会
          <rt>であ</rt>
        </ruby>
  いの
        <ruby>
          記念日
          <rt>きねんび </rt>
        </ruby>{' '}
        <ruby>
          荒
          <rt>あ</rt>
        </ruby>
  れた
        <ruby>
          頬
          <rt>ほほ</rt>
        </ruby>
  に あたたかい
        <ruby>
          キス
          <rt>きす</rt>
        </ruby>
  をくれたね
      </span>

      <span>
        <ruby>
          泣
          <rt>な</rt>
        </ruby>
  き
        <ruby>
          ベソ
          <rt>べそ</rt>
        </ruby>
  の
        <ruby>
          顔
          <rt>かお</rt>
        </ruby>
  ひどく
        <ruby>
          汚
          <rt>よご</rt>
        </ruby>
  れて{' '}
        <ruby>
          一緒
          <rt>いっしょ</rt>
        </ruby>
  に
        <ruby>
          笑
          <rt>わら</rt>
        </ruby>
  ったよね
      </span>

      <span>
  もう
        <ruby>
          覚
          <rt>おぼ</rt>
        </ruby>
  えている{' '}
        <ruby>
          全部
          <rt>ぜんぶ</rt>
        </ruby>
  が
        <ruby>
          青
          <rt>あお</rt>
        </ruby>
  になる
      </span>
      <span>
  あの
        <ruby>
          日
          <rt>ひ</rt>
        </ruby>
  よりも
        <ruby>
          少
          <rt>すこ</rt>
        </ruby>
  し
        <ruby>
          遠
          <rt>とお</rt>
        </ruby>
  くで{' '}
        <ruby>
          今
          <rt>いま</rt>
        </ruby>
        <ruby>
          伝
          <rt>つた</rt>
        </ruby>
  えたいことが
      </span>
      <span>
        <ruby>
          君
          <rt>きみ</rt>
        </ruby>
  も
        <ruby>
          大人
          <rt>おとな</rt>
        </ruby>
  になったら{' '}
        <ruby>
          恋
          <rt>こい</rt>
        </ruby>
  をするんだよ
      </span>
      <span>
        <ruby>
          運命
          <rt>うんめい</rt>
        </ruby>
  の
        <ruby>
          人
          <rt>ひと</rt>
        </ruby>
  に
        <ruby>
          出会
          <rt>であ</rt>
        </ruby>
  うまでは{' '}
        <ruby>
          傷
          <rt>きず</rt>
        </ruby>
  が
        <ruby>
          絶
          <rt>た</rt>
        </ruby>
  えないかもだけど
      </span>
      <span>
        <ruby>
          悲
          <rt>かな</rt>
        </ruby>
  しみなんかは{' '}
        <ruby>
          気
          <rt>き</rt>
        </ruby>
  づけば
        <ruby>
          雨
          <rt>あめ</rt>
        </ruby>
  になる
      </span>
      <span>
        <ruby>
          心
          <rt>こころ</rt>
        </ruby>
        <ruby>
          耕
          <rt>たがや</rt>
        </ruby>
  し{' '}
        <ruby>
          花
          <rt>はな</rt>
        </ruby>
  が
        <ruby>
          咲
          <rt>さ</rt>
        </ruby>
  くまで
      </span>
      <span>
        <ruby>
          可愛
          <rt>かわい</rt>
        </ruby>
  く
        <ruby>
          揺
          <rt>ゆ</rt>
        </ruby>
  れなよ{' '}
        <ruby>
          双葉
          <rt>ふたば</rt>
        </ruby>
      </span>
      <span>
        <ruby>
          約束
          <rt>やくそく</rt>
        </ruby>
  の
        <ruby>
          春
          <rt>はる</rt>
        </ruby>
  が
        <ruby>
          訪
          <rt>おとず</rt>
        </ruby>
  れて あたたかい
        <ruby>
          空気
          <rt>くうき</rt>
        </ruby>
  をこぼして
      </span>
      <span>
  まるで
        <ruby>
          君
          <rt>きみ</rt>
        </ruby>
  との
        <ruby>
          会話
          <rt>かいわ</rt>
        </ruby>
  みたいで{' '}
        <ruby>
          幸
          <rt>しあわ</rt>
        </ruby>
  せ、って
        <ruby>
          今
          <rt>いま</rt>
        </ruby>
        <ruby>
          思
          <rt>おも</rt>
        </ruby>
  ったよ
      </span>
      <span>
  ずっと
        <ruby>
          忘
          <rt>わす</rt>
        </ruby>
  れないで{' '}
        <ruby>
          胸
          <rt>むね</rt>
        </ruby>
  の
        <ruby>
          中
          <rt>なか</rt>
        </ruby>
  に
        <ruby>
          落
          <rt>お</rt>
        </ruby>
  ちて
      </span>
      <span>
        <ruby>
          誰
          <rt>だれ</rt>
        </ruby>
  も
        <ruby>
          知
          <rt>し</rt>
        </ruby>
  らないところで いつかまた{' '}
        <ruby>
          瞳
          <rt>ひとみ</rt>
        </ruby>
  を
        <ruby>
          覗
          <rt>のぞ</rt>
        </ruby>
  かせて
      </span>
      <span>
        <ruby>
          君
          <rt>きみ</rt>
        </ruby>
  が
        <ruby>
          大人
          <rt>おとな</rt>
        </ruby>
  になったら{' '}
        <ruby>
          見
          <rt>み</rt>
        </ruby>
  つけるその
        <ruby>
          夢
          <rt>ゆめ</rt>
        </ruby>
  を
      </span>
      <span>
        <ruby>
          限
          <rt>かぎ</rt>
        </ruby>
  りなく
        <ruby>
          側
          <rt>そば</rt>
        </ruby>
  で
        <ruby>
          見
          <rt>み</rt>
        </ruby>
  ていたくても もう
        <ruby>
          叶
          <rt>かな</rt>
        </ruby>
  わないらしいからさ
      </span>
      <span>
        <ruby>
          喜
          <rt>よろこ</rt>
        </ruby>
  び
        <ruby>
          全部
          <rt>ぜんぶ</rt>
        </ruby>
  を
        <ruby>
          空
          <rt>そら</rt>
        </ruby>
  に
        <ruby>
          巻
          <rt>ま</rt>
        </ruby>
  き
        <ruby>
          散
          <rt>ち</rt>
        </ruby>
  らして
      </span>
      <span>
        <ruby>
          伝
          <rt>つた</rt>
        </ruby>
  えて
        <ruby>
          欲
          <rt>ほ</rt>
        </ruby>
  しいよ
        <ruby>
          双葉
          <rt>ふたば</rt>
        </ruby>
      </span>
      <span>
        <ruby>
          涙
          <rt>なみだ</rt>
        </ruby>
  の
        <ruby>
          謎
          <rt>なぞ</rt>
        </ruby>
  を
        <ruby>
          教
          <rt>おし</rt>
        </ruby>
  えて
      </span>
      <span>
  もう
        <ruby>
          一度
          <rt>いちど</rt>
        </ruby>
        <ruby>
          会
          <rt>あ</rt>
        </ruby>
  いたいけれど
      </span>
      <span>
        <ruby>
          君
          <rt>きみ</rt>
        </ruby>
  の
        <ruby>
          夢
          <rt>ゆめ</rt>
        </ruby>
  の
        <ruby>
          中
          <rt>なか</rt>
        </ruby>
  へ{' '}
        <ruby>
          遊
          <rt>あそ</rt>
        </ruby>
  びに
        <ruby>
          行
          <rt>ゆ</rt>
        </ruby>
  くからね
      </span>
      <span>
        <ruby>
          心
          <rt>こころ</rt>
        </ruby>
  の
        <ruby>
          傷
          <rt>きず</rt>
        </ruby>
  も
        <ruby>
          酷
          <rt>ひど</rt>
        </ruby>
  い
        <ruby>
          言葉
          <rt>ことば</rt>
        </ruby>
  も{' '}
        <ruby>
          受
          <rt>う</rt>
        </ruby>
  け
        <ruby>
          止
          <rt>と</rt>
        </ruby>
  めてあげるぞ
      </span>
      <span>
        <ruby>
          君
          <rt>きみ</rt>
        </ruby>
  も
        <ruby>
          大人
          <rt>おとな</rt>
        </ruby>
  になったら{' '}
        <ruby>
          恋
          <rt>こい</rt>
        </ruby>
  をするんだよ
      </span>
      <span>
        <ruby>
          運命
          <rt>うんめい</rt>
        </ruby>
  の
        <ruby>
          人
          <rt>ひと</rt>
        </ruby>
  に
        <ruby>
          出会
          <rt>であ</rt>
        </ruby>
  うまでは{' '}
        <ruby>
          傷
          <rt>きず</rt>
        </ruby>
  が
        <ruby>
          絶
          <rt>た</rt>
        </ruby>
  えないかもだけど
      </span>
      <span>
        <ruby>
          悲
          <rt>かな</rt>
        </ruby>
  しみなんかは{' '}
        <ruby>
          気
          <rt>き</rt>
        </ruby>
  づけば
        <ruby>
          雨
          <rt>あめ</rt>
        </ruby>
  になる
      </span>
      <span>
        <ruby>
          心
          <rt>こころ</rt>
        </ruby>
        <ruby>
          耕
          <rt>たがや</rt>
        </ruby>
  し{' '}
        <ruby>
          花
          <rt>はな</rt>
        </ruby>
  が
        <ruby>
          咲
          <rt>さ</rt>
        </ruby>
  くまで
      </span>
      <span>
        <ruby>
          可愛
          <rt>かわい</rt>
        </ruby>
  く
        <ruby>
          揺
          <rt>ゆ</rt>
        </ruby>
  れなよ{' '}
        <ruby>
          双葉
          <rt>ふたば</rt>
        </ruby>
      </span>
      <span>
        <ruby>
          可愛
          <rt>かわい</rt>
        </ruby>
  く
        <ruby>
          揺
          <rt>ゆ</rt>
        </ruby>
  れなよ{' '}
        <ruby>
          双葉
          <rt>ふたば</rt>
        </ruby>
      </span>
      <span>
        <ruby>
          可愛
          <rt>かわい</rt>
        </ruby>
  く
        <ruby>
          揺
          <rt>ゆ</rt>
        </ruby>
  れなよ{' '}
        <ruby>
          双葉
          <rt>ふたば</rt>
        </ruby>
      </span>

    </div>
  );
}